Repository enjin/platform-fuel-tanks, pull requests merged in 2023-07, with the labels that each got.

#8 Use new method
  src/Rules/IsFuelTankOwner.php
Labels: bug

#9 Removes amphp dependencies
  composer.json
  phpunit.xml
  testbench.yaml
Labels: dependencies

#10 Increase coverage
  database/factories/AccountRuleFactory.php
  phpunit.xml
  src/Models/Laravel/FuelTank.php
  tests/Feature/GraphQL/Resources/GetFuelTank.graphql
  tests/Unit/TankServiceTest.php
Labels: enhancement
