Repository enjin/platform-fuel-tanks, pull requests merged in 2024-07, with the labels that each got.

#52 [PLA-1876] Supports new v1010 on sync
  composer.json
  src/Models/Substrate/DispatchRulesParams.php
  src/Models/Substrate/RequireSignatureParams.php
  src/Services/Processor/Substrate/Codec/Decoder.php
Labels: enhancement, Review effort [1-5]: 3, Other

#55 [PLA-1882] Wrap codes with db transaction
  src/GraphQL/Mutations/DispatchMutation.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#59 [PLA-1900] Adds default value to provides deposit
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankCreated.php
Labels: Bug fix, Review effort [1-5]: 1
