Repository enjin/platform-fuel-tanks, pull requests merged in 2024-06, with the labels that each got.

#44 [PLA-1805] Broadcast events changes
  src/Events/Substrate/FuelTanks/AccountAdded.php
  src/Events/Substrate/FuelTanks/AccountRemoved.php
  src/Events/Substrate/FuelTanks/CallDispatched.php
  src/Events/Substrate/FuelTanks/FreezeStateMutated.php
  src/Events/Substrate/FuelTanks/FuelTankCreated.php
  src/Events/Substrate/FuelTanks/FuelTankDestroyed.php
  src/Events/Substrate/FuelTanks/FuelTankMutated.php
  src/Events/Substrate/FuelTanks/MutateFreezeStateScheduled.php
  src/Events/Substrate/FuelTanks/RuleSetInserted.php
  src/Events/Substrate/FuelTanks/RuleSetRemoved.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/AccountAdded.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/AccountRemoved.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/AccountRuleDataRemoved.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/CallDispatched.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FreezeStateMutated.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankCreated.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankDestroyed.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankMutated.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/RuleSetInserted.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/RuleSetRemoved.php
  testbench.yaml
  tests/Unit/EncodingTest.php
Labels: enhancement, Review effort [1-5]: 3, Tests

#45 [PLA-1806] Fixes missing function arguments
  src/Enums/Substrate/FuelTanksEventType.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#46 [PLA-1806] Class init error
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankCreated.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankMutated.php
Labels: Review effort [1-5]: 2, Bug fix

#48 [PLA-1678] Laravel 11 update.
  .github/workflows/run_tests.yml
  composer.json
  phpunit.xml
  src/Enums/Substrate/StorageKey.php
  src/Models/FuelTank.php
  src/Models/FuelTankAccount.php
  src/Models/Substrate/AccountRulesParams.php
  src/Models/Substrate/DispatchRulesParams.php
  src/Models/Substrate/MaxFuelBurnPerTransactionParams.php
  src/Models/Substrate/RequireTokenParams.php
  src/Models/Substrate/TankFuelBudgetParams.php
  src/Models/Substrate/UserAccountManagementParams.php
  src/Models/Substrate/UserFuelBudgetParams.php
  src/Models/Substrate/WhitelistedCollectionsParams.php
  src/Models/Substrate/WhitelistedPalletsParams.php
  src/Models/Wallet.php
  src/Rules/AccountsExistsInFuelTank.php
  src/Rules/AccountsNotInFuelTank.php
  src/Rules/TokenExistsInCollection.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/AccountRuleDataRemoved.php
  src/Services/TransactionService.php
  testbench.yaml
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#50 [PLA-1693] Set path for improved local testing.
  src/FuelTanksServiceProvider.php
Labels: enhancement, Review effort [1-5]: 2

#51 [PLA-1693] Improved local testing tweaks.
  src/FuelTanksServiceProvider.php
  src/Package.php
Labels: enhancement, Review effort [1-5]: 2
