Repository enjin/platform-fuel-tanks, pull requests merged in 2024-11, with the labels that each got.

#72 [PLA-1938] Fixes RuleSetInserted
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/AccountAdded.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankCreated.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/RuleSetInserted.php
  tests/Feature/GraphQL/Mutations/DispatchTest.php
Labels: Review effort [1-5]: 1

#71 [PLA-1975] Add custom queue
  config/enjin-platform-fuel-tanks.php
  src/Events/Substrate/FuelTanks/AccountAdded.php
  src/Events/Substrate/FuelTanks/AccountRemoved.php
  src/Events/Substrate/FuelTanks/CallDispatched.php
  src/Events/Substrate/FuelTanks/FreezeStateMutated.php
  src/Events/Substrate/FuelTanks/FuelTankCreated.php
  src/Events/Substrate/FuelTanks/FuelTankDestroyed.php
  src/Events/Substrate/FuelTanks/FuelTankMutated.php
  src/Events/Substrate/FuelTanks/RuleSetInserted.php
  src/Events/Substrate/FuelTanks/RuleSetRemoved.php
  src/Traits/HasCustomQueue.php
Labels: Review effort [1-5]: 2

#74 [PLA-2055] Fixes RuleSets on CreateFuelTank
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/FuelTankCreated.php
  src/Services/Processor/Substrate/Events/Implementations/FuelTanks/RuleSetInserted.php
Labels: Review effort [1-5]: 3

#70 [PLA-2052][PLA-2103] Fix PermittedExtrinsic on CreateFuelTank and InsertRuleSet
  src/GraphQL/Mutations/CreateFuelTankMutation.php
  src/GraphQL/Mutations/InsertRuleSetMutation.php
  src/Models/Substrate/DispatchRulesParams.php
  src/Models/Substrate/PermittedExtrinsicsParams.php
  src/Rules/AccountsExistsInFuelTank.php
  src/Rules/AccountsNotInFuelTank.php
  src/Rules/CanDispatch.php
  src/Rules/FuelTankExists.php
  src/Rules/IsFuelTankOwner.php
  src/Rules/RuleSetExists.php
  src/Rules/RuleSetNotExists.php
  src/Rules/TokenExistsInCollection.php
  src/Rules/ValidMutation.php
  tests/Feature/GraphQL/Mutations/CreateFuelTankTest.php
  tests/Feature/GraphQL/Mutations/InsertRuleSetTest.php
  tests/Unit/EncodingTest.php
Labels: Review effort [1-5]: 2
